[package]
name = "tick"
version = "0.1.0"
authors = ["Nathan Lilienthal <nathan@nixpulvis.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "=0.2.0-alpha.6"
